# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 14ab36061b2e2fbedd58272e42ce52de58b48b9c6ff427266d5bddb9f4568377aef26993923bd2d2cc7eb1a709949d39ccbda3588b49947bdf5787eac9ee81a5

test:
  secret_key_base: 8d372d8abb6113e7779f45e2c2067d3890797808a44a6fae8788c13a5d7832e4add235e2d4ffe8b267b369b378b1616b221334a0131280be1124467b816ab444

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
